version: '2'

services:
    elasticsearch:
        image: elasticsearch
        container_name: elasticsearch
        volumes:
            - /docker/elasticsearch/data:/usr/share/elasticsearch/data
        networks:
            - net_dev_stack

    logstash:
        image: logstash
        container_name: logstash
        volumes:
            - /docker/logstash/config:/etc/logstash/conf.d
        depends_on:
            - elasticsearch
        ports:
            - "9733:9733"
            - "9733:9733/udp"
        networks:
            - net_dev_stack
        command: logstash -f /etc/logstash/conf.d/
    
    kibana:
        image: kibana
        container_name: kibana
        depends_on:
            - elasticsearch
            - logstash
        ports:
            - "9730:5601"
        networks:
            - net_dev_stack
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
    
    gogs:
        image: gogs/gogs
        container_name: gogs
        volumes:
            - /docker/gogs:/data
        ports:
            - "9700:3000"
        networks:
            - net_dev_stack
    
    sonarqube_mysql:
        image: mysql
        container_name: sonarqube_mysql
        volumes:
            - /docker/sonarqube/mysql:/var/lib/mysql
        networks:
            - net_dev_stack
        environment:
            - MYSQL_ROOT_PASSWORD=mysql 
            - MYSQL_DATABASE=sonar 
            - MYSQL_USER=sonar 
            - MYSQL_PASSWORD=sonar
    
    sonarqube:
        image: sonarqube
        container_name: sonarqube
        depends_on:
            - sonarqube_mysql
        ports:
            - "9710:9000"
        networks:
            - net_dev_stack
        environment:
            - SONARQUBE_JDBC_USERNAME=sonar 
            - SONARQUBE_JDBC_PASSWORD=sonar 
            - SONARQUBE_JDBC_URL=jdbc:mysql://sonarqube_mysql/sonar?useUnicode=true&characterEncoding=utf8
    
    jenkins:
        image: jenkins
        container_name: jenkins
        depends_on:
            - gogs
            - sonarqube
        volumes:
            - /docker/jenkins:/var/jenkins_home
        ports:
            - "9720:8080"
        networks:
            - net_dev_stack
        environment:
            - JAVA_OPTS="-Duser.timezone=Europe/Berlin"

networks:
  net_dev_stack:
    driver: bridge
